# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

"""Authorisation rules observer."""

import logging
import os
import signal
import subprocess
from importlib.resources import files
from pathlib import Path
from sys import version_info

from ops.charm import CharmEvents
from ops.framework import EventBase, EventSource, Object
from ops.model import ActiveStatus

from single_kernel_postgresql.config.literals import CONTAINER_NAME
from single_kernel_postgresql.core.state import CharmState

logger = logging.getLogger(__name__)

# File path for the spawned authorisation rules observer process to write logs.
LOG_FILE_PATH = "/var/log/authorisation_rules_observer.log"

# The observer script ships inside the library package instead of the charm's
# scripts/ directory; the spawned interpreter resolves it from site-packages.
OBSERVER_SCRIPT = "authorisation_rules_observer.py"


class DatabasesChangeEvent(EventBase):
    """A custom event for databases changes."""


class AuthorisationRulesChangeCharmEvents(CharmEvents):
    """A CharmEvents extension for authorisation rules changes.

    Includes :class:`DatabasesChangeEventt` in those that can be handled.
    """

    databases_change = EventSource(DatabasesChangeEvent)


class AuthorisationRulesObserver(Object):
    """Observes authorisation rules changes.

    Args:
        charm: the charm that is instantiating the library.
        state: the charm state.
        run_cmd: run command to use to dispatch events.
    """

    def __init__(self, charm, state: CharmState, run_cmd: str):
        super().__init__(charm, "authorisation-rules-observer")

        self.charm = charm
        self.state = state
        self._run_cmd = run_cmd

    def start_authorisation_rules_observer(self):
        """Start the authorisation rules observer running in a new process."""
        container = self.charm.unit.get_container(CONTAINER_NAME)
        if (
            not isinstance(self.charm.unit.status, ActiveStatus)
            or self.state.peer_relation is None
            or not container.can_connect()
            or not self.state.application.is_cluster_initialised
        ):
            return

        if "authorisation-rules-observer-pid" in self.state.peer.data:
            pid = int(self.state.peer.data["authorisation-rules-observer-pid"])
            try:
                os.kill(pid, 0)  # Check if the process exists
                return
            except OSError:
                pass

        logger.info("Starting the authorisation rules observer")

        # We need to trick Juju into thinking that we are not running
        # in a hook context, as Juju will disallow use of juju-run.
        new_env = os.environ.copy()
        new_env.pop("JUJU_CONTEXT_ID", None)
        # Generate the venv path based on the existing lib path
        for loc in new_env["PYTHONPATH"].split(":"):
            path = Path(loc)
            venv_path = (
                path
                / ".."
                / "venv"
                / "lib"
                / f"python{version_info.major}.{version_info.minor}"
                / "site-packages"
            )
            if path.stem == "lib":
                new_env["PYTHONPATH"] = f"{venv_path.resolve()}:{new_env['PYTHONPATH']}"
                break

        urls = [
            self.state.patroni_url.replace(str(self.state.endpoint), endpoint)
            for endpoint in self.state.endpoints
        ]

        script_path = str(files("single_kernel_postgresql.scripts").joinpath(OBSERVER_SCRIPT))

        # Input is generated by the charm
        process = subprocess.Popen(  # noqa: S603
            [
                "/usr/bin/python3",
                script_path,
                ",".join(urls),
                self._run_cmd,
                self.charm.unit.name,
                self.charm.charm_dir,
            ],
            # File shouldn't close
            stdout=open(LOG_FILE_PATH, "a"),  # noqa: SIM115
            stderr=subprocess.STDOUT,
            env=new_env,
        )

        self.state.peer.data.update({"authorisation-rules-observer-pid": str(process.pid)})
        logger.info(f"Started authorisation rules observer process with PID {process.pid}")

    def stop_authorisation_rules_observer(self):
        """Stop the authorisation rules observer process."""
        if (
            self.state.peer_relation is None
            or "authorisation-rules-observer-pid" not in self.state.peer.data
        ):
            return

        authorisation_rules_observer_pid = int(
            self.state.peer.data["authorisation-rules-observer-pid"]
        )

        try:
            os.kill(authorisation_rules_observer_pid, signal.SIGTERM)
            logger.info(
                f"Stopped authorisation rules observer process with PID {authorisation_rules_observer_pid}"
            )
            del self.state.peer.data["authorisation-rules-observer-pid"]
        except OSError:
            pass
