# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

"""Cluster topology changes observer."""

import logging
import os
import signal
import subprocess
from importlib.resources import files
from pathlib import Path
from sys import version_info

from charmlibs.systemd import daemon_reload, service_enable
from jinja2 import Template
from ops import ActiveStatus, CharmEvents, EventBase, EventSource, Object

from single_kernel_postgresql.config.enums import Substrates
from single_kernel_postgresql.core.state import CharmState
from single_kernel_postgresql.utils import render_file

logger = logging.getLogger(__name__)

# File path for the spawned cluster topology observer process to write logs.
LOG_FILE_PATH = "/var/log/cluster_topology_observer.log"

# The observer scripts and the raft-observer systemd templates ship inside the
# library package instead of the charm's scripts/ and templates/ directories.
SCRIPTS_PACKAGE = "single_kernel_postgresql.scripts"
TEMPLATES_PACKAGE = "single_kernel_postgresql.templates"


class ClusterTopologyChangeEvent(EventBase):
    """A custom event for cluster topology changes."""


class DatabasesChangeEvent(EventBase):
    """A custom event for databases changes."""


class RaftReconnectEvent(EventBase):
    """A custom event for databases changes."""


class ClusterTopologyChangeCharmEvents(CharmEvents):
    """A CharmEvents extension for cluster topology changes.

    Includes :class:`ClusterTopologyChangeEvent` in those that can be handled.
    """

    cluster_topology_change = EventSource(ClusterTopologyChangeEvent)
    databases_change = EventSource(DatabasesChangeEvent)
    raft_reconnect = EventSource(RaftReconnectEvent)


class ClusterTopologyObserver(Object):
    """Observes changing topology in the cluster.

    Observed cluster topology changes cause :class"`ClusterTopologyChangeEvent` to be emitted.
    """

    def __init__(self, charm, state: CharmState, run_cmd: str) -> None:
        """Constructor for ClusterTopologyObserver.

        Args:
            charm: the charm that is instantiating the library.
            state: the charm state.
            run_cmd: run command to use to dispatch events.
        """
        super().__init__(charm, "cluster-topology-observer")

        self.charm = charm
        self.state = state
        self._run_cmd = run_cmd

    def start_observer(self) -> None:
        """Start the cluster topology observer running in a new process."""
        if (
            not isinstance(self.charm.unit.status, ActiveStatus)
            or self.state.peer_relation is None
        ):
            return
        if "observer-pid" in self.state.peer.data:
            # Double check that the PID exists
            pid = int(self.state.peer.data["observer-pid"])
            try:
                os.kill(pid, 0)
                return
            except OSError:
                pass
        if not self.state.unit_ip:
            logging.info("Cannot start cluster topology observer process: No IP set")
            return

        logging.info("Starting cluster topology observer process")

        # We need to trick Juju into thinking that we are not running
        # in a hook context, as Juju will disallow use of juju-run.
        new_env = os.environ.copy()
        if "JUJU_CONTEXT_ID" in new_env:
            new_env.pop("JUJU_CONTEXT_ID")
        # Generate the venv path based on the existing lib path
        for loc in new_env["PYTHONPATH"].split(":"):
            path = Path(loc)
            venv_path = (
                path
                / ".."
                / "venv"
                / "lib"
                / f"python{version_info.major}.{version_info.minor}"
                / "site-packages"
            )
            if path.stem == "lib":
                new_env["PYTHONPATH"] = f"{venv_path.resolve()}:{new_env['PYTHONPATH']}"
                break

        urls = [self.state.patroni_url] + [
            self.state.patroni_url.replace(self.state.unit_ip, peer)
            for peer in list(self.state.peer_members_ips)
        ]

        script_path = str(files(SCRIPTS_PACKAGE).joinpath("cluster_topology_observer.py"))

        # Input is generated by the charm
        pid = subprocess.Popen(  # noqa: S603
            [
                "/usr/bin/python3",
                script_path,
                ",".join(urls),
                self._run_cmd,
                self.charm.unit.name,
                self.charm.charm_dir,
            ],
            # File shouldn't close
            stdout=open(LOG_FILE_PATH, "a"),  # noqa: SIM115
            stderr=subprocess.STDOUT,
            env=new_env,
        ).pid

        self.state.peer.data.update({"observer-pid": f"{pid}"})
        logging.info(f"Started cluster topology observer process with PID {pid}")

    def stop_observer(self):
        """Stop the running observer process if we have previously started it."""
        if self.state.peer_relation is None or "observer-pid" not in self.state.peer.data:
            return

        if stored_pid := self.state.peer.data.get("observer-pid"):
            observer_pid = int(stored_pid)

            try:
                os.kill(observer_pid, signal.SIGINT)
                msg = "Stopped running cluster topology observer process with PID {}"
                logging.info(msg.format(observer_pid))
                self.state.peer.data.update({"observer-pid": ""})
            except OSError:
                pass


def copy_environment() -> dict[str, str]:
    """Environment variables to pass to a script."""
    new_env = os.environ.copy()
    if "JUJU_CONTEXT_ID" in new_env:
        new_env.pop("JUJU_CONTEXT_ID")
    # Generate the venv path based on the existing lib path
    for loc in new_env["PYTHONPATH"].split(":"):
        path = Path(loc)
        venv_path = (
            path
            / ".."
            / "venv"
            / "lib"
            / f"python{version_info.major}.{version_info.minor}"
            / "site-packages"
        )
        if path.stem == "lib":
            new_env["PYTHONPATH"] = f"{venv_path.resolve()}:{new_env['PYTHONPATH']}"
            break
    return {var: val for var, val in new_env.items() if "JUJU" in var or "PATH" in var}


def start_raft_observer() -> None:
    """Render systemd units and start the observer."""
    timer_service_file = "/etc/systemd/system/raft-observer.timer"
    oneshot_service_file = "/etc/systemd/system/raft-observer.service"

    service_template = Template(
        files(TEMPLATES_PACKAGE).joinpath("vm/raft-observer.service.j2").read_text()
    )

    rendered = service_template.render(
        envvars=copy_environment(),
        # The raft observer script ships inside the library package.
        script=str(files(SCRIPTS_PACKAGE).joinpath("raft_observer.py")),
    )
    render_file(Substrates.VM, oneshot_service_file, rendered, 0o644, change_owner=False)

    timer_template = Template(
        files(TEMPLATES_PACKAGE).joinpath("vm/raft-observer.timer.j2").read_text()
    )

    rendered = timer_template.render()
    render_file(Substrates.VM, timer_service_file, rendered, 0o644, change_owner=False)

    # Reload systemd to pick up the new service
    daemon_reload()
    service_enable(timer_service_file, "--now")
    logger.info("Installed and enabled raft observer timer")
