# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

"""Observer scripts manager."""

import logging
import os
import signal
import subprocess
from pathlib import Path
from sys import version_info
from typing import TYPE_CHECKING

from ops import ActiveStatus

from single_kernel_postgresql.config.enums import Substrates
from single_kernel_postgresql.managers.base import BaseManager

if TYPE_CHECKING:
    from single_kernel_postgresql.core.state import CharmState
    from single_kernel_postgresql.workload.base import BaseWorkload


logger = logging.getLogger(__name__)

# File path for the spawned cluster topology observer process to write logs.
LOG_FILE_PATH = "/var/log/cluster_topology_observer.log"
RUN_CMD = "/usr/bin/juju-exec"


class ObserverManager(BaseManager):
    """Handles cross substrate observer scripts."""

    def __init__(self, state: "CharmState", workload: "BaseWorkload") -> None:
        super().__init__(state, workload, "observer_manager")

    def start_observer(self) -> None:
        """Start the cluster topology observer running in a new process."""
        if (
            not isinstance(self.state.peer.unit.status, ActiveStatus)
            or self.state.peer_relation is None
        ):
            return
        if self.state.substrate == Substrates.VM:
            pid = self.state.peer.observer_pid
        else:
            pid = self.state.peer.authorisation_rules_observer_pid
        if pid:
            # Double check that the PID exists
            try:
                os.kill(pid, 0)
                return
            except OSError:
                pass
        if not self.state.unit_ip:
            logging.info("Cannot start cluster topology observer process: No IP set")
            return

        logging.info("Starting cluster topology observer process")

        # We need to trick Juju into thinking that we are not running
        # in a hook context, as Juju will disallow use of juju-run.
        new_env = os.environ.copy()
        if "JUJU_CONTEXT_ID" in new_env:
            new_env.pop("JUJU_CONTEXT_ID")
        # Generate the venv path based on the existing lib path
        for loc in new_env["PYTHONPATH"].split(":"):
            path = Path(loc)
            venv_path = (
                path
                / ".."
                / "venv"
                / "lib"
                / f"python{version_info.major}.{version_info.minor}"
                / "site-packages"
            )
            if path.stem == "lib":
                new_env["PYTHONPATH"] = f"{venv_path.resolve()}:{new_env['PYTHONPATH']}"
                break

        urls = [self.state.patroni_url] + [
            self.state.patroni_url.replace(self.state.unit_ip, peer)
            for peer in list(self.state.peer_members_ips)
        ]

        # Input is generated by the charm
        script = (
            "single_kernel_postgresql.scripts.cluster_topology_observer"
            if self.state.substrate == Substrates.VM
            else "single_kernel_postgresql.scripts.authorisation_rules_observer"
        )
        pid = subprocess.Popen(  # noqa: S603
            [
                "/usr/bin/python3",
                "-m",
                script,
                ",".join(urls),
                RUN_CMD,
                self.state.model.unit.name,
                self.state.framework.charm_dir,
            ],
            # File shouldn't close
            stdout=open(LOG_FILE_PATH, "a"),  # noqa: SIM115
            stderr=subprocess.STDOUT,
            env=new_env,
        ).pid

        if self.state.substrate == Substrates.VM:
            self.state.peer.observer_pid = pid
        else:
            self.state.peer.authorisation_rules_observer_pid = pid
        logging.info(f"Started observer process with PID {pid}")

    def stop_observer(self):
        """Stop the running observer process if we have previously started it."""
        if self.state.peer_relation is None:
            return

        if self.state.substrate == Substrates.VM:
            pid = self.state.peer.observer_pid
        else:
            pid = self.state.peer.authorisation_rules_observer_pid
        if pid:
            try:
                os.kill(pid, signal.SIGINT)
                msg = "Stopped running cluster topology observer process with PID {}"
                logging.info(msg.format(pid))
                self.state.peer.observer_pid = None
            except OSError:
                pass


def copy_environment() -> dict[str, str]:
    """Environment variables to pass to a script."""
    new_env = os.environ.copy()
    if "JUJU_CONTEXT_ID" in new_env:
        new_env.pop("JUJU_CONTEXT_ID")
    # Generate the venv path based on the existing lib path
    for loc in new_env["PYTHONPATH"].split(":"):
        path = Path(loc)
        venv_path = (
            path
            / ".."
            / "venv"
            / "lib"
            / f"python{version_info.major}.{version_info.minor}"
            / "site-packages"
        )
        if path.stem == "lib":
            new_env["PYTHONPATH"] = f"{venv_path.resolve()}:{new_env['PYTHONPATH']}"
            break
    return {var: val for var, val in new_env.items() if "JUJU" in var or "PATH" in var}
